# Generated by Django 6.1.1 on 2026-09-29 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100, verbose_name='name')),
                ('content', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='product_images/2026/09/28/samsung23fe.png', upload_to='product_images/%Y/%m/%d/')),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, choices=[('phone', 'phone'), ('laptop', 'laptop')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
